In [50]:
# Image Processing:
# Input: Image 
# Output: 19x19 Array

# Scoring:
# Inputs: 19x19 Array + B/W Prisoners  
# Outputs: B/W Territories, Dame, Captured B/W Stones 

class Board():
    
    def __init__(self, size, state, white_capped, black_capped): 
        self.size = size
        self.white_capped = white_capped
        self.black_capped = black_capped
        self.state = state # boardsize x boardsize array containing -1,1, and 0
    
    def get_neighbors(self, i, j):
        #Returns offset from [i,j] with identity in format ((x offset, y offset), identity)
        directions = {
        'left': [-1, 0],
        'right': [1, 0],
        'top': [0, -1],
        'bottom': [0, 1]
        }
        neighbors = []

        for direction, offset in directions.items():
            x, y = i + offset[0], j + offset[1]
            if 0 <= x < self.size and 0 <= y < self.size:
                neighbor_identity = self.state[x,y]
                neighbors.append((offset[0], offset[1], neighbor_identity))

        return neighbors
    
    def get_group(self, i, j):
        queue = [(i, j)]  # Initialize with the starting stone's coordinates
        visited = set()  # Initialize an empty set to store visited stones
        group = []

        start_identity = self.state[i,j]  # Identity of the starting stone
        group.append(((i, j), start_identity))  # Add the starting stone to the group

        while len(queue) > 0:
            stone = queue.pop(0)  # Retrieve the first stone from the queue
            visited.add(stone)  # Mark the stone as visited
            stone_identity = self.state[stone[0], stone[1]]  # Identity of the stone

            for neighbor in self.get_neighbors(stone[0], stone[1]):
                neighbor_coords = (stone[0] + neighbor[0], stone[1] + neighbor[1])
                neighbor_identity = neighbor[2]  # Identity of the neighboring stone
                if neighbor_coords not in visited and neighbor_identity == start_identity:
                    queue.append(neighbor_coords)
                    visited.add(neighbor_coords)
                    group.append((neighbor_coords, neighbor_identity))  # Add neighboring stone to the group

        return group
    
    def get_liberties(self, i, j):
        liberties = set()
        group = self.get_group(i, j)

        for stone_coords, _ in group:
            stone_neighbors = self.get_neighbors(stone_coords[0], stone_coords[1])
            for neighbor in stone_neighbors:
                neighbor_coords = (stone_coords[0] + neighbor[0], stone_coords[1] + neighbor[1])
                if neighbor_coords not in group and self.state[neighbor_coords[0]][neighbor_coords[1]] == 0:
                    liberties.add(neighbor_coords)
        return len(liberties)

    def is_valid(self):
        # Check to see if there are any groups with no liberties.
        for i in range(self.size):
            for j in range(self.size):
                if self.state[i,j] != 0:
                    if self.get_liberties(i,j) == 0:
                        return False
                
        return True
    
    def get_score(self): 
        if is_valid():
            
            black_score = 0
            white_score = 0
            
            visited = set() # Contains the coordinates of visited stones
            
            for i in range(self.size):
                for j in range(self.size):
                    start_identity = self.state[i,j]
                    
                    queue = [(i, j)] 
                    group = [] # Contains the coordinates of the empty group
                    
                    if self.state[i,j] not in visited 
                        visited.add([i,j])
                        
                        if self.state[i,j] == 0:
                            while len(queue) > 0:
                                stone = queue.pop(0)
                                
                                
                        
                        
            
        else: # Board not valid
            print("Board is not valid")
            
        pass
        
    
            

In [55]:
import numpy as np
i,j = 3,0



BOARDSIZE = 9
sampleState = np.zeros((BOARDSIZE, BOARDSIZE))

sampleState[4,0:7] = -1
sampleState[5, 6:] = -1
sampleState[1,4] = -1
sampleState[3,:] = 1
sampleState[4,8] = 1
sampleState[7,4] = 1
sampleState[1,0] = -1
sampleState[0,0] = 1
sampleState[0,1] = -1
print(sampleState)

# In the 19x19 array, black stone = 1, white stone = -1, empty = 0

sampleBoard = Board(BOARDSIZE, sampleState, 0, 0)

val = sampleBoard.is_valid()
print(val)

    

[[ 1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]
False


1